run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - bodyclose

linters-settings:
  gosec:
    excludes:
      - G104   # errcheck handles this
  revive:
    rules:
      - name: var-naming
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
