apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudy-readonly
  labels:
    app.kubernetes.io/name: cloudy
    app.kubernetes.io/component: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudy-readonly
subjects:
  - kind: ServiceAccount
    name: cloudy
    namespace: cloudy
