package config

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// CurrentSchemaVersion is bumped whenever the shape of Profile or
// ContextProfile changes in a backward-incompatible way. Saved profiles with
// an older version are considered invalid and must be regenerated.
const CurrentSchemaVersion = 1

// Profile is the discovered cluster profile written to ~/.cloudy/profile.yaml.
// It is generated by the "cloudy setup" / probe flow and cached between runs.
type Profile struct {
	// SchemaVersion allows forward-compatible deserialization. Always compare
	// against CurrentSchemaVersion before trusting the content.
	SchemaVersion int `yaml:"schema_version"`

	// GeneratedAt is the wall-clock time when the profile was last written.
	GeneratedAt time.Time `yaml:"generated_at"`

	// Contexts is the list of probed Kubernetes contexts.
	Contexts []ContextProfile `yaml:"contexts"`

	// RecommendedSkills lists the skill names that the probe flow determined
	// are applicable to the discovered cluster topology.
	RecommendedSkills []string `yaml:"recommended_skills"`
}

// ContextProfile captures the observed topology and capabilities of a single
// Kubernetes context.
type ContextProfile struct {
	// Name matches the context name from kubeconfig.
	Name string `yaml:"name"`

	// Reachable is true when the API server responded during probing.
	Reachable bool `yaml:"reachable"`

	// K8sVersion is the server version string (e.g. "v1.28.5"), if available.
	K8sVersion string `yaml:"k8s_version,omitempty"`

	// NodeCount is the total number of nodes observed.
	NodeCount int `yaml:"node_count"`

	// GPUNodeCount is the number of nodes that expose nvidia.com/gpu resources.
	GPUNodeCount int `yaml:"gpu_node_count"`

	// Namespaces is the list of namespaces visible to the probe credentials.
	Namespaces []string `yaml:"namespaces,omitempty"`

	// PodSampleScanned is true when setup attempted to inspect pods for hints.
	PodSampleScanned bool `yaml:"pod_sample_scanned,omitempty"`

	// PodSampleCount is the number of pods inspected for setup hints.
	PodSampleCount int `yaml:"pod_sample_count,omitempty"`

	// PodSampleIncomplete is true when setup could not inspect every visible
	// pod because the scan hit its safety cap or a list page failed.
	PodSampleIncomplete bool `yaml:"pod_sample_incomplete,omitempty"`

	// PodSampleIncompleteReason explains why PodSampleIncomplete is true.
	// Stable values include cap and list_error.
	PodSampleIncompleteReason string `yaml:"pod_sample_incomplete_reason,omitempty"`

	// JVMPodCount is the count of pods whose images suggest a JVM runtime.
	// Deprecated compatibility field; new setup scans also populate
	// RuntimePodCounts["jvm"].
	JVMPodCount int `yaml:"jvm_pod_count"`

	// PythonPodCount is the count of pods whose images suggest a Python runtime.
	// Deprecated compatibility field; new setup scans also populate
	// RuntimePodCounts["python"].
	PythonPodCount int `yaml:"python_pod_count"`

	// RuntimePodCounts counts detected application runtime families by stable
	// lowercase key, for example go, node, jvm, python, ruby, dotnet, or native.
	// It is a best-effort setup hint for recommendations, not a support boundary.
	RuntimePodCounts map[string]int `yaml:"runtime_pod_counts,omitempty"`

	// FrontendPodCount is the count of pods whose names, labels, env, or images
	// suggest a browser-facing web/frontend workload.
	FrontendPodCount int `yaml:"frontend_pod_count"`

	// IngressHostCount is the number of Ingress host/default-backend surfaces
	// visible to setup probing.
	IngressHostCount int `yaml:"ingress_host_count"`

	// HasFrontendSurface indicates that setup saw at least one browser-facing
	// workload or Ingress surface.
	HasFrontendSurface bool `yaml:"has_frontend_surface"`

	// HasMetricsServer indicates whether the metrics-server API is available.
	HasMetricsServer bool `yaml:"has_metrics_server"`

	// HasPrometheus indicates whether at least one Prometheus instance was found.
	HasPrometheus bool `yaml:"has_prometheus"`

	// HasDCGMExporter indicates whether the NVIDIA DCGM exporter is present.
	HasDCGMExporter bool `yaml:"has_dcgm_exporter"`

	// HasOTel indicates whether OpenTelemetry collector pods were detected.
	HasOTel bool `yaml:"has_otel"`

	// PrometheusURLs holds the discovered Prometheus base URLs for this context.
	PrometheusURLs []string `yaml:"prometheus_urls,omitempty"`

	// Permissions is the result of probing SelfSubjectAccessReview against
	// every (group, resource, verb) cloudy needs to operate. Empty when the
	// API server was unreachable. The /setup wizard surfaces these so users
	// see actual RBAC capability, not just connectivity.
	Permissions []PermissionCheck `yaml:"permissions,omitempty"`
}

// PermissionCheck is the outcome of a single SelfSubjectAccessReview probe.
type PermissionCheck struct {
	// Group is the API group ("" = core, e.g. "apps", "metrics.k8s.io").
	Group string `yaml:"group,omitempty"`

	// Resource is the resource name in the kube API (pods, nodes, …).
	Resource string `yaml:"resource"`

	// Subresource is the optional sub-resource (e.g. "log" for pods/log).
	Subresource string `yaml:"subresource,omitempty"`

	// Verb is one of get / list / watch.
	Verb string `yaml:"verb"`

	// Allowed reports whether the API server granted the verb.
	Allowed bool `yaml:"allowed"`

	// Reason carries the server-provided denial reason when Allowed is false.
	Reason string `yaml:"reason,omitempty"`
}

// LoadProfile reads a Profile from path. If the file does not exist it returns
// a zero-value Profile and a nil error; callers should check IsValid() or
// Expired() before trusting the result.
func LoadProfile(path string) (Profile, error) {
	var p Profile

	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return p, nil
	}
	if err != nil {
		return p, fmt.Errorf("profile: read %s: %w", path, err)
	}
	if err := yaml.Unmarshal(data, &p); err != nil {
		return p, fmt.Errorf("profile: parse %s: %w", path, err)
	}
	return p, nil
}

// SaveProfile writes p to path as YAML using an atomic write (temp + rename)
// with 0600 permissions. Parent directories are created if necessary.
func SaveProfile(path string, p Profile) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("profile: mkdir %s: %w", filepath.Dir(path), err)
	}

	data, err := yaml.Marshal(p)
	if err != nil {
		return fmt.Errorf("profile: marshal: %w", err)
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), ".cloudy-profile-*.yaml")
	if err != nil {
		return fmt.Errorf("profile: create temp: %w", err)
	}
	tmpName := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("profile: write temp: %w", err)
	}
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("profile: chmod temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("profile: close temp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("profile: rename to %s: %w", path, err)
	}
	return nil
}

// ProfilePath returns the resolved path to the cluster profile file.
// Resolution order matches Path: $CLOUDY_HOME, then $XDG_CONFIG_HOME/cloudy,
// then ~/.cloudy.
func ProfilePath() string {
	if ch := os.Getenv("CLOUDY_HOME"); ch != "" {
		return filepath.Join(ch, "profile.yaml")
	}
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "cloudy", "profile.yaml")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".cloudy", "profile.yaml")
	}
	return filepath.Join(home, ".cloudy", "profile.yaml")
}

// Expired reports whether the profile is stale. A zero GeneratedAt is always
// considered expired.
func (p Profile) Expired(ttl time.Duration) bool {
	if p.GeneratedAt.IsZero() {
		return true
	}
	return time.Since(p.GeneratedAt) > ttl
}

// IsValid reports whether the profile can be trusted: it must carry the
// current schema version and contain at least one context entry.
func (p Profile) IsValid() bool {
	return p.SchemaVersion == CurrentSchemaVersion && len(p.Contexts) > 0
}
